version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:474495984432:task-definition/airqualitycicd:4"
        LoadBalancerInfo:
          ContainerName: "aircicdcontainer"
          ContainerPort: "80"
        PlatformVersion: "LATEST"