version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n0j1m4d6
    - IMAGE_NAME=air_quality_ecr
    - IMAGE_URI=public.ecr.aws/n0j1m4d6/air_quality_ecr:latest
    - CONTAINER_NAME=aircicdcontainer
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_NAME
    - mvn clean package -Ddockerfile.skip
    - docker build -t $IMAGE_NAME .
  post_build:
    commands:
    - echo Build completed on `date`
    - echo $(docker images)
    - docker tag $IMAGE_NAME $IMAGE_URI
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json
